name: relation
version: '0.1.0.0'
synopsis: Data structure for Many-to-Many relation
category: Data Structures
author: Koji Miyazato
maintainer: viercc@gmail.com
copyright: Koji Miyazato
license: BSD3
homepage: https://github.com/minkless/relation#readme
extra-source-files:
- README.md
ghc-options:
- -Wall
- -O2
dependencies:
- containers
library:
  source-dirs: src
  ghc-options:
  - -fwarn-redundant-constraints
  exposed-modules:
  - Data.Relation
  - Data.Relation.Class
  - Data.Relation.Naive
  - Data.Relation.Both
  - Data.Relation.LTR
  - Data.Relation.RTL
  dependencies:
  - base >=4.7 && <5
tests:
  relation-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -fno-warn-orphans
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - relation
    - QuickCheck
    - hspec
